name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  DEBIAN_FRONTEND: noninteractive

jobs:
  lychee:
    name: QA (Lychee)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - name: Run Lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --cache --max-cache-age 1d .

  cargo-machete:
    name: QA (Cargo Machete)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-machete
      - name: Run cargo-machete
        run: cargo machete --skip-target-dir

  pre-commit:
    name: QA (pre-commit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
        env:
          # fmt is failing to download on CI
          SKIP: fmt
      - name: Run rustfmt
        run: cargo fmt --all -- --check

  test:
    name: Test
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          # Rust problem matchers make the real output
          # of *.stderr diffs impossible to read.
          matcher: false
      - name: Install Dylint
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-dylint,dylint-link
      - name: Run unit tests
        run: cargo test --all
